---
- name: 'template broker.cfg'
  template:
    src: broker.cfg.j2
    dest: /etc/shinken/brokers/broker.cfg
  notify:
    - restart shinken

- name: 'list file in modules directory'
  command: ls -1 /etc/shinken/modules
  failed_when: shinken_module_files.rc > 2
  always_run: true
  changed_when: false
  register: shinken_module_files

- name: 'delete unused file'
  file: path=/etc/shinken/modules/{{item}} state=absent
  with_items: shinken_module_files.stdout_lines|difference(shinken_keep_mod_files)
  notify:
    - restart shinken
