- name: 'set correct pinning for wheezy'
  copy:
    content: |
      Package: *
      Pin: release n=wheezy
      Pin-Priority: 800
    dest: /etc/apt/preferences.d/wheezy

- name: 'setup jessie repository'
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian/ jessie main'
    update_cache: yes

- name: 'set correct pinning for shinken'
  copy:
    content: |
      Package: shinken*
      Pin: release n=jessie
      Pin-Priority: 950
    dest: /etc/apt/preferences.d/shinken
